### ISSUE TITLE
No support of @client directive

### ISSUE THREAD

**Issue by yairopro** [apollographql/vscode-graphql#60]
![](https://user-images.githubusercontent.com/8110568/156556608-e51eb9b2-bc18-41ab-ba55-4c49c0b8aa6e.png)

**Comment by Fxlr8** [comment]
There is an easy fix for that:

Create a local graphql schema file if you don't have one and add the following line to the beginning:

clientSchema.graphql
```graphql
directive @client on FIELD

```

Then add that client schema to your .graphqlrc.yml like that
```yml
schema:
  - https://some-remote-schema.net/api/graphql
  - clientSchema.graphql # <- here
documents: "src/**/*.{graphql,js,ts,jsx,tsx}"
```

Done
